try {
    fnInexistente();
} catch {
    console.log("esto es un error!");
}